# Generated by Django 5.0.1 on 2024-01-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=20),
        ),
    ]
