# Generated by Django 4.2 on 2024-02-02 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0002_alter_mailing_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='time_of_day',
            field=models.TimeField(default=datetime.datetime(2024, 2, 2, 23, 18, 6, 942315, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
